name: build

on:
  push:
  pull_request:
  schedule:
    - cron: "51 3 * * 6" # Runs at 03:51, only on Saturday
jobs:
  build:
    name: build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install dependencies
        run: shards install --without-development --release
      - name: Run tests
        run: crystal spec
      - name: Build executable
        run: shards build --release
      - name: Run executable (help)
        run: bin/vvsay --help
      - name: Check dependent libraries (macOS)
        if: matrix.os == 'macos'
        run: otool -L bin/vvsay
      - uses: actions/upload-artifact@v4
        with:
          name: vvsay-cli-${{ matrix.os }}
          path: bin/${{ matrix.os == 'windows' && 'vvsay.exe' || 'vvsay' }}
}
