name: build

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
  schedule:
    - cron: "51 3 * * 6" # Runs at 03:51, only on Saturday

jobs:
  build:
    name: build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Set version variables
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${{ github.ref_name }}
          else
            VERSION="build-$(date +%Y%m%d-%H%M%S)"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BIN=vvsay" >> $GITHUB_ENV

      - name: Install dependencies
        if: matrix.target != 'x86_64-unknown-linux-musl'
        run: shards install --without-development

      - name: Run tests
        if: matrix.target != 'x86_64-unknown-linux-musl'
        run: crystal spec

      - name: Build on Linux (musl)
        if: matrix.target == 'x86_64-unknown-linux-musl'
        shell: bash
        run: |
          mkdir -p bin
          docker run -d --name alpine -v $GITHUB_WORKSPACE:/workspace -w /workspace crystallang/crystal:latest-alpine tail -f /dev/null
          docker exec alpine apk add zlib-static zlib-dev openssl-libs-static openssl-dev pcre2-dev pcre2-static libgc-dev libevent-static libevent-dev zstd-static zstd-dev
          docker exec alpine shards install --without-development --release --static
          docker exec alpine crystal spec
          docker exec alpine shards build --release --static
          docker exec alpine chmod +x bin/$BIN
          ldd bin/$BIN || echo "Static binary (no dynamic dependencies)"
          file bin/$BIN
          bin/$BIN --help
          bin/$BIN --version
          PKG=vvsay-${VERSION}-${{ matrix.target }}
          mkdir -p $PKG
          cp bin/$BIN $PKG/
          cp LICENSE $PKG/
          cp README.md $PKG/
          tar czf $PKG.tar.gz $PKG

      - name: Build on Linux (gnu)
        if: matrix.target == 'x86_64-unknown-linux-gnu'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev zlib1g-dev libpcre2-dev libgc-dev libevent-dev libzstd-dev
          shards install --without-development --release
          crystal spec
          shards build --release --static
          chmod +x bin/$BIN
          ldd bin/$BIN || echo "Static binary (no dynamic dependencies)"
          file bin/$BIN
          bin/$BIN --help
          bin/$BIN --version
          PKG=vvsay-${VERSION}-${{ matrix.target }}
          mkdir -p $PKG
          cp bin/$BIN $PKG/
          cp LICENSE $PKG/
          cp README.md $PKG/
          tar czf $PKG.tar.gz $PKG

      - name: Build on macOS
        if: contains(matrix.target, 'apple-darwin')
        shell: bash
        run: |
          shards install --without-development --release
          brew update
          brew install libgc pcre2 openssl@3 zlib libevent zstd
          echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
          unset PKG_CONFIG_PATH
          echo "cleared PKG_CONFIG_PATH to avoid openSSL conflicts"
          ln -s $(brew ls libgc | grep libgc.a) .
          ln -s $(brew ls pcre2 | grep libpcre2-8.a) .
          ln -s $(brew ls openssl@3 | grep libssl.a) .
          ln -s $(brew ls openssl@3 | grep libcrypto.a) .
          ln -s $(brew ls zlib | grep libz.a) .
          ln -s $(brew ls libevent | grep libevent.a) .
          ln -s $(brew ls zstd | grep libzstd.a) .
          STATIC_LIBS="-L $(pwd) $(pwd)/libgc.a $(pwd)/libpcre2-8.a $(pwd)/libssl.a $(pwd)/libcrypto.a $(pwd)/libz.a $(pwd)/libevent.a $(pwd)/libzstd.a -Wl,-search_paths_first"
          crystal spec
          shards build --link-flags="$STATIC_LIBS" --release
          chmod +x bin/$BIN
          otool -L bin/$BIN
          if otool -L bin/$BIN | grep homebrew; then
            echo "Error: Homebrew dependencies detected!"
            exit 1
          fi
          echo "Static linking successful"
          file bin/$BIN
          bin/$BIN --help
          bin/$BIN --version
          PKG=vvsay-${VERSION}-${{ matrix.target }}
          mkdir -p $PKG
          cp bin/$BIN $PKG/
          cp LICENSE $PKG/
          cp README.md $PKG/
          tar czf $PKG.tar.gz $PKG

      - name: Build on Windows (MSVC)
        if: matrix.target == 'x86_64-pc-windows-msvc'
        shell: pwsh
        run: |
          shards install --without-development --release
          crystal spec
          shards build --release --static --link-flags="-lucrt"
          bin/vvsay --help
          bin/vvsay --version
          $pkg = "vvsay-$env:VERSION-${{ matrix.target }}"
          mkdir $pkg
          Copy-Item "bin/$env:BIN.exe" "$pkg/"
          Copy-Item "LICENSE" "$pkg/"
          Copy-Item "README.md" "$pkg/"
          Compress-Archive -Path "$pkg/*" -DestinationPath "$pkg.zip"

      - name: Upload artifacts (non-release)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: vvsay-${{ matrix.target }}
          path: |
            vvsay-*.tar.gz
            vvsay-*.zip

      - name: Upload release assets (release only)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            vvsay-*.tar.gz
            vvsay-*.zip
